baseURL = "https://jlucktay.dev/"
languageCode = "en-au"
theme = "m10c"
title = "James Lucktaylor"

[params]
  author = "James Lucktaylor"
  description = "Dev, gamer, husband."
  avatar = "og-image.webp"

  [[params.social]]
    name = "github"
    url = "https://github.com/jlucktay"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.com/in/jlucktay"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/jlucktay"

[taxonomies]
  category = "categories"
  director = "directors"
  tag = "tags"
