baseURL = "https://jlucktay.dev/"
languageCode = "en-au"
title = "Nest Tales"
theme = "archie"
timeZone = "Europe/London"
copyright = "© James Lucktaylor"

[params]
mode = "toggle" # color-mode → light,dark,toggle,auto

subtitle = """
New year, new blog?
We'll see how often I manage a post.
Maybe just start out with some [notes](https://v5.chriskrycho.com/notes/noteblogging/)?"""

# Socials

[[params.social]]
name = "Bluesky"
icon = "at-sign"
url = "https://bsky.app/profile/jlucktay.dev"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/jlucktay"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/jlucktay"

# Main menu

### TODO(jlucktay): write this page; take inspiration from here: https://v5.chriskrycho.com/about/
# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3
