version: 2
updates:
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: ts-jest
    versions:
    - 26.5.2
  - dependency-name: typescript
    versions:
    - 4.2.2
