---
name: Deploy Cloudflare Worker

on:
  push:
    branches:
      - # Matches the exact name of a branch or tag name.
        main
    paths:
      - # This workflow.
        .github/workflows/deploy-cloudflare-worker.yaml
      - # Any files in this directory and its subdirectories at the root of the repository.
        go-jlucktay-dev-cf-worker/**

# Allow only one concurrent deployment.
concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

# Default to bash.
defaults:
  run:
    shell: bash

jobs:
  deploy-cloudflare-worker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Deploy to Cloudflare Workers with Wrangler
        uses: cloudflare/wrangler-action@9acf94ace14e7dc412b076f2c5c20b8ce93c79cd # v3.15.0
        with:
          workingDirectory: go-jlucktay-dev-cf-worker
          wranglerVersion: latest
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
